apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-demo-k8s
spec:
  selector:
    matchLabels:
      app: mysql-test
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mysql-test
    spec:
      containers:
      - name: mysql-test
        image: demoburneraccount/ci-testing:mysql
        ports:
        - containerPort: 3306